from tkinter import * #PARA IMPORTAR ELEMENTOS DE LA LIBRERÍA
import tkinter #IMPORTA TODA LA GALERÍA
v0=Tk()#VENTANA PRINCIPAL
v0.greometry("200x200")
v0.mainloop()#RULO PRINCIPAL QUE REFLEJA LOS 
#PROCESOS DEL PROGRAMA

